apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  dbPassword: {{ .Values.secret.dbPassword | b64enc | quote }}
  awsToken: {{ .Values.secret.awsToken | b64enc | quote }}