# Default values for Helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2  
image:
  repository: rawaabha/service-crafter
  pullPolicy: IfNotPresent
  tag: "0.1"  
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000  

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local  # Change as needed
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /health  # Adjust to your health check endpoint
    port: http

readinessProbe:
  httpGet:
    path: /health  # Adjust to your health check endpoint
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
config:
  nodeEnv: ""            
  appPort: ""               
  databaseUrl: ""  
  apiUrl: "" 

secret:
  dbPassword: "your-database-password"  
  awsToken: "your-aws-token"              
