apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: service1
          - name: service2
  template:
    metadata:
      name: '{{name}}'  
      namespace: default
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Bha-Rawaa/argocd-test.git'  
        targetRevision: Infra-testt
        path: helm
        helm:
          valueFiles:
            - values/{{name}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
